//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using Assets.BlijftDatZo.Scripts;

public class SoundPlayer
{
	private GameController gameController;
	private AudioClip[] soundsA;
	private AudioClip[] soundsB;
	
	public SoundPlayer()
	{
		this.gameController = GameSceneController.Instance.GameController;
		this.soundsA = this.gameController.GetAudioClipsA ();
		this.soundsB = this.gameController.GetAudioClipsB ();
	}

	public void PlayA(AudioSource source)
	{
		Play (source, this.soundsA);
	}

	public void PlayB(AudioSource source)
	{
		Play (source, this.soundsB);
	}

	private void Play(AudioSource source, AudioClip[] clips)
	{
		int clipIndex = Random.Range (0, clips.Length);
		//Debug.Log ("clip index = " + clipIndex);
		source.clip = clips [clipIndex];
		//source.pitch = Random.Range(0.9f, 1.1f);
		source.Play ();
	}
}

